name: dart_opengl
description: Dart bindings for the Open Graphics Library
version: 2.0.0
repository: https://github.com/gliscowo/dart_opengl

publish_to: https://pub.wispforest.io

environment:
  sdk: ^3.10.0

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0

dev_dependencies:
  ffigen: ^20.0.0
  lints: ^6.0.0
  logging: ^1.3.0
  test: ^1.21.0
  vector_math: ^2.2.0
